-- rezyserzy 
insert into rezyserzy (imie, nazwisko) values ('Brit', 'Alvin');
insert into rezyserzy (imie, nazwisko) values ('Langsdon', 'MacKim');
insert into rezyserzy (imie, nazwisko) values ('Tedi', 'Aris');
insert into rezyserzy (imie, nazwisko) values ('Rivalee', 'Prier');
insert into rezyserzy (imie, nazwisko) values ('Errol', 'Coyte');

-- gatunki
insert into gatunki (nazwa) values ('Drama');
insert into gatunki (nazwa) values ('Crime');
insert into gatunki (nazwa) values ('Comedy');
insert into gatunki (nazwa) values ('Romance');
insert into gatunki (nazwa) values ('Horror');

-- dane osobowe
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Rolf', 'Trudgeon', 'rtrudgeon0@reference.com', '865 860 152');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Bren', 'Quarrie', 'bquarrie1@cdbaby.com', '998 687 451');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Malory', 'McNeil', 'mmcneil2@cam.ac.uk', '654 217 272');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Henriette', 'Eves', 'heves3@dell.com', '679 164 189');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Nissie', 'Averay', 'naveray4@godaddy.com', '561 876 684');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Melosa', 'Druery', 'mdruery5@microsoft.com', '331 597 920');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Edd', 'MacMeanma', 'emacmeanma6@mlb.com', '451 116 253');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Susanne', 'Levine', 'slevine7@rakuten.co.jp', '118 320 517');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Ernst', 'Celez', 'ecelez8@flickr.com', '763 562 141');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Scotti', 'Baile', 'sbaile9@marketwatch.com', '838 754 223');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Regen', 'Cotesford', 'rcotesforda@mayoclinic.com', '742 122 155');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Arnold', 'Laible', 'alaibleb@storify.com', '762 247 243');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Geno', 'Bushell', 'gbushellc@github.com', '701 219 828');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Petr', 'Russan', 'prussand@meetup.com', '194 287 947');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Clayborne', 'Chainey', 'cchaineye@ed.gov', '306 591 199');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Mickie', 'Wyrall', 'mwyrallf@printfriendly.com', '713 277 470');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Faina', 'Asch', 'faschg@stumbleupon.com', '569 525 555');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Dilan', 'Bevis', 'dbevish@surveymonkey.com', '541 747 471');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Yasmeen', 'Stansfield', 'ystansfieldi@ning.com', '549 473 105');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Addi', 'McAlinion', 'amcalinionj@163.com', '337 803 649');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Suzanne', 'Skewis', 'sskewisk@alibaba.com', '676 417 691');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Dillon', 'Peinke', 'dpeinkel@lycos.com', '372 912 732');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Khalil', 'Grindall', 'kgrindallm@buzzfeed.com', '836 807 132');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Jenifer', 'Gallichan', 'jgallichann@goodreads.com', '194 458 632');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Hephzibah', 'McCart', 'hmccarto@bandcamp.com', '861 164 900');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Roselia', 'Maestro', 'rmaestrop@nps.gov', '360 341 192');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Brigitte', 'McCauley', 'bmccauleyq@usatoday.com', '360 649 334');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Fredi', 'Graundisson', 'fgraundissonr@arizona.edu', '684 257 575');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Tonnie', 'Sapp', 'tsapps@comsenz.com', '285 265 123');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Arabele', 'Crowth', 'acrowtht@dropbox.com', '500 948 072');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kylynn', 'Neesham', 'kneesham0@booking.com', '357 485 919');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Catharine', 'Verdey', 'cverdey1@desdev.cn', '794 471 703');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Loni', 'Parnall', 'lparnall2@opera.com', '911 174 134');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Monica', 'Shardlow', 'mshardlow3@omniture.com', '775 485 345');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Frances', 'Kelner', 'fkelner4@craigslist.org', '666 383 175');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Marney', 'Shottin', 'mshottin5@nyu.edu', '606 562 077');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Ignatius', 'McCarver', 'imccarver6@scribd.com', '940 479 306');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Clarabelle', 'Beardsley', 'cbeardsley7@ft.com', '567 922 520');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Terri-jo', 'Folling', 'tfolling8@census.gov', '481 240 633');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Katuscha', 'Walczynski', 'kwalczynski9@ocn.ne.jp', '441 761 343');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Adria', 'Whitechurch', 'awhitechurcha@list-manage.com', '457 716 335');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Alejandrina', 'Plowman', 'aplowmanb@ca.gov', '820 918 181');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Anselma', 'MacConnulty', 'amacconnultyc@tmall.com', '446 152 592');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Corina', 'Goble', 'cgobled@imdb.com', '477 542 679');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Natala', 'Yitzhak', 'nyitzhake@naver.com', '394 773 236');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Bernadine', 'Sokill', 'bsokillf@geocities.com', '866 945 302');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kelsey', 'Lanfare', 'klanfareg@4shared.com', '512 360 183');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Denny', 'Burkill', 'dburkillh@omniture.com', '672 934 098');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Aylmer', 'Barehead', 'abareheadi@nymag.com', '147 926 714');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Alphonse', 'Bowden', 'abowdenj@tumblr.com', '647 571 098');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Hilario', 'Haithwaite', 'hhaithwaitek@sphinn.com', '131 772 701');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kali', 'Tarbath', 'ktarbathl@discovery.com', '623 200 493');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Wendye', 'De Bruyne', 'wdebruynem@4shared.com', '833 949 202');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Brandice', 'Arnell', 'barnelln@wikia.com', '765 839 835');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Billye', 'Seargeant', 'bseargeanto@joomla.org', '318 888 546');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Shanna', 'Mac Giolla Pheadair', 'smacgiollapheadairp@hao123.com', '154 304 764');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Piotr', 'Cozzi', 'pcozziq@bloglovin.com', '440 365 747');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Jaquelin', 'Hurich', 'jhurichr@prlog.org', '698 371 871');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Gianina', 'Knott', 'gknotts@deliciousdays.com', '527 435 150');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Berry', 'Varvell', 'bvarvellt@reverbnation.com', '201 113 966');

-- sprzedawcy
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('RT70', 88931654393, '2017/09/01', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('BQ71', 33816419431, '2017/06/21', '2018/10/21');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MM72', 59375667404, '2017/09/21', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('HE73', 84279823169, '2017/10/24', '2018/06/28');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('NA74', 74210686127, '2017/12/30', '2018/05/02');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MD75', 10385738753, '2017/11/02', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('EM76', 57807381607, '2017/04/20', '2018/03/10');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('SL77', 46378394318, '2017/12/01', '2018/10/19');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('EC78', 93214684573, '2017/07/06', '2018/10/31');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('SB79', 76410197023, '2017/07/11', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('RC80', 14690409001, '2017/01/06', '2018/08/25');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('AL81', 34778424560, '2017/05/03', '2018/04/08');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('GB82', 44662013189, '2017/06/02', '2018/10/12');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('PR83', 28792684220, '2017/05/30', '2018/12/17');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('CC84', 48152409771, '2017/01/19', '2018/04/14');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MW85', 92732148969, '2017/07/26', '2018/07/07');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('FA86', 69173229348, '2017/12/20', '2018/08/17');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('DB87', 95142101615, '2017/07/14', '2018/05/07');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('YS88', 70650784376, '2017/03/21', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('AM89', 54538188084, '2017/01/30', '2018/04/30');

--filmy
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C71', 'Power and Terror: Noam Chomsky in Our Times', '29/04/2018', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C72', 'After Dark, My Sweet', '27/01/2018', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'R73', 'Devil to Pay!, The', '19/02/2016', 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'C71', 'Conversation, The', '05/06/2017', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'D70', 'Shinobi No Mono 4: Siege', '03/02/2016', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', 'Treasure Island', '02/02/2018', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'C72', 'Big Steal, The', '10/07/2017', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'T75', 'Mrs. Brown''s Boys D''Movie', '24/03/2017', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Mexican, The', '27/11/2017', 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C72', 'Cold Storage', '20/09/2018', 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'C71', 'Bodyguard, The (Karate Kiba)', '20/05/2017', 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'H74', 'L''instant et la patience ', '21/12/2016', 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'H74', 'Flintstone Kids'' Just Say No Special, The', '10/03/2016', 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'R73', 'Dirigible', '22/05/2016', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C71', 'Billy the Kid', '19/11/2018', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'C71', 'Piano Teacher, The (La pianiste)', '01/03/2018', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'M76', 'Stuck Between Stations', '28/02/2016', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'H74', 'Stateside', '09/06/2018', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Funny Thing Happened on the Way to the Forum, A', '29/11/2016', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'R73', 'Mr. Jealousy', '13/11/2018', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C71', 'Ice Age Columbus: Who Were the First Americans?', '01/08/2017', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', '10.5: Apocalypse', '26/03/2016', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'M76', 'One Foot in Heaven', '03/08/2016', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Oxford Blues', '06/12/2017', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'R73', 'Mad Ron''s Prevues from Hell', '01/05/2017', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'R73', 'Galaxy of Terror (Quest)', '08/02/2018', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C71', 'Bird of Prey', '14/09/2017', 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'R73', 'Sharknado', '28/08/2018', 'odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'D70', 'Bruno (Dress Code, The)', '29/11/2016', 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Divide, The', '16/08/2018', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C72', 'Beauty and the Beast (Belle et la bête, La)', '16/03/2018', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', '2012: Time for Change', '26/07/2018', 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'H74', 'Transformers: Age of Extinction', '25/05/2018', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', 'David and Bathsheba', '10/09/2016', 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', 'Devil Inside, The', '11/12/2018', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', 'Dorado, El', '06/05/2017', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'M76', 'Spare Parts', '18/01/2016', 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'C71', 'Clubland (a.k.a. Introducing the Dwights)', '09/09/2018', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'M76', 'Devil', '18/08/2018', 'libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'T75', 'Golden Boy', '06/07/2018', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'D70', 'Family Viewing', '20/02/2018', 'justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'D70', 'Theatre Bizarre, The', '27/10/2018', 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'M76', 'Hans Christian Andersen', '31/12/2018', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'H74', 'Prata Palomares', '19/11/2017', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Glass-blower''s Children, The (Glasblåsarns barn)', '05/01/2018', 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'C72', 'Infestation', '13/09/2016', 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'C72', 'Extreme Justice', '05/07/2018', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'R73', 'Almost You', '30/01/2018', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'M76', 'Louisiana Story', '08/08/2016', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'C72', 'Driven', '11/01/2019', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras');

-- miejsca

