-- iv. elementy interakcyjne w poleceniach SQL – parametryzacja poleceń SQL
-- v. agregowania danych (użycie frazy group by) – na podstawie jednej lub wielu tabel
-- vi. agregowania danych (użycie frazy having) – na podstawie jednej lub wielu tabel
-- vii. wykorzystujące funkcje związane z obsługą daty i czasu, arytmetyczne, znakowe
-- viii. zapytania zagnieżdżone
-- ix. zapytania zagnieżdżone z agregowaniem danych (rollup, cube)
-- x. utworzenie tabeli tymczasowej na podstawie jednej lub wielu tabel