-- dane osobowe
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Rolf', 'Trudgeon', 'rtrudgeon0@reference.com', '865 860 152');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Bren', 'Quarrie', 'bquarrie1@cdbaby.com', '998 687 451');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Malory', 'McNeil', 'mmcneil2@cam.ac.uk', '654 217 272');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Henriette', 'Eves', 'heves3@dell.com', '679 164 189');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Nissie', 'Averay', 'naveray4@godaddy.com', '561 876 684');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Melosa', 'Druery', 'mdruery5@microsoft.com', '331 597 920');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Edd', 'MacMeanma', 'emacmeanma6@mlb.com', '451 116 253');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Susanne', 'Levine', 'slevine7@rakuten.co.jp', '118 320 517');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Ernst', 'Celez', 'ecelez8@flickr.com', '763 562 141');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Scotti', 'Baile', 'sbaile9@marketwatch.com', '838 754 223');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Regen', 'Cotesford', 'rcotesforda@mayoclinic.com', '742 122 155');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Arnold', 'Laible', 'alaibleb@storify.com', '762 247 243');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Geno', 'Bushell', 'gbushellc@github.com', '701 219 828');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Petr', 'Russan', 'prussand@meetup.com', '194 287 947');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Clayborne', 'Chainey', 'cchaineye@ed.gov', '306 591 199');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Mickie', 'Wyrall', 'mwyrallf@printfriendly.com', '713 277 470');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Faina', 'Asch', 'faschg@stumbleupon.com', '569 525 555');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Dilan', 'Bevis', 'dbevish@surveymonkey.com', '541 747 471');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Yasmeen', 'Stansfield', 'ystansfieldi@ning.com', '549 473 105');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Addi', 'McAlinion', 'amcalinionj@163.com', '337 803 649');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Suzanne', 'Skewis', 'sskewisk@alibaba.com', '676 417 691');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Dillon', 'Peinke', 'dpeinkel@lycos.com', '372 912 732');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Khalil', 'Grindall', 'kgrindallm@buzzfeed.com', '836 807 132');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Jenifer', 'Gallichan', 'jgallichann@goodreads.com', '194 458 632');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Hephzibah', 'McCart', 'hmccarto@bandcamp.com', '861 164 900');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Roselia', 'Maestro', 'rmaestrop@nps.gov', '360 341 192');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Brigitte', 'McCauley', 'bmccauleyq@usatoday.com', '360 649 334');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Fredi', 'Graundisson', 'fgraundissonr@arizona.edu', '684 257 575');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Tonnie', 'Sapp', 'tsapps@comsenz.com', '285 265 123');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Arabele', 'Crowth', 'acrowtht@dropbox.com', '500 948 072');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kylynn', 'Neesham', 'kneesham0@booking.com', '357 485 919');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Catharine', 'Verdey', 'cverdey1@desdev.cn', '794 471 703');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Loni', 'Parnall', 'lparnall2@opera.com', '911 174 134');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Monica', 'Shardlow', 'mshardlow3@omniture.com', '775 485 345');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Frances', 'Kelner', 'fkelner4@craigslist.org', '666 383 175');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Marney', 'Shottin', 'mshottin5@nyu.edu', '606 562 077');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Ignatius', 'McCarver', 'imccarver6@scribd.com', '940 479 306');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Clarabelle', 'Beardsley', 'cbeardsley7@ft.com', '567 922 520');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Terri-jo', 'Folling', 'tfolling8@census.gov', '481 240 633');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Katuscha', 'Walczynski', 'kwalczynski9@ocn.ne.jp', '441 761 343');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Adria', 'Whitechurch', 'awhitechurcha@list-manage.com', '457 716 335');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Alejandrina', 'Plowman', 'aplowmanb@ca.gov', '820 918 181');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Anselma', 'MacConnulty', 'amacconnultyc@tmall.com', '446 152 592');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Corina', 'Goble', 'cgobled@imdb.com', '477 542 679');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Natala', 'Yitzhak', 'nyitzhake@naver.com', '394 773 236');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Bernadine', 'Sokill', 'bsokillf@geocities.com', '866 945 302');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kelsey', 'Lanfare', 'klanfareg@4shared.com', '512 360 183');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Denny', 'Burkill', 'dburkillh@omniture.com', '672 934 098');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Aylmer', 'Barehead', 'abareheadi@nymag.com', '147 926 714');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Alphonse', 'Bowden', 'abowdenj@tumblr.com', '647 571 098');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Hilario', 'Haithwaite', 'hhaithwaitek@sphinn.com', '131 772 701');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Kali', 'Tarbath', 'ktarbathl@discovery.com', '623 200 493');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Wendye', 'De Bruyne', 'wdebruynem@4shared.com', '833 949 202');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Brandice', 'Arnell', 'barnelln@wikia.com', '765 839 835');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Billye', 'Seargeant', 'bseargeanto@joomla.org', '318 888 546');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Shanna', 'Mac Giolla Pheadair', 'smacgiollapheadairp@hao123.com', '154 304 764');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Piotr', 'Cozzi', 'pcozziq@bloglovin.com', '440 365 747');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Jaquelin', 'Hurich', 'jhurichr@prlog.org', '698 371 871');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Gianina', 'Knott', 'gknotts@deliciousdays.com', '527 435 150');
insert into dane_osobowe (imie, nazwisko, email, telefon) values ('Berry', 'Varvell', 'bvarvellt@reverbnation.com', '201 113 966');

-- sprzedawcy
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('RT70', 88931654393, '2017/09/01', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('BQ71', 33816419431, '2017/06/21', '2018/10/21');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MM72', 59375667404, '2017/09/21', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('HE73', 84279823169, '2017/10/24', '2018/06/28');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('NA74', 74210686127, '2017/12/30', '2018/05/02');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MD75', 10385738753, '2017/11/02', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('EM76', 57807381607, '2017/04/20', '2018/03/10');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('SL77', 46378394318, '2017/12/01', '2018/10/19');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('EC78', 93214684573, '2017/07/06', '2018/10/31');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('SB79', 76410197023, '2017/07/11', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('RC80', 14690409001, '2017/01/06', '2018/08/25');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('AL81', 34778424560, '2017/05/03', '2018/04/08');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('GB82', 44662013189, '2017/06/02', '2018/10/12');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('PR83', 28792684220, '2017/05/30', '2018/12/17');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('CC84', 48152409771, '2017/01/19', '2018/04/14');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('MW85', 92732148969, '2017/07/26', '2018/07/07');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('FA86', 69173229348, '2017/12/20', '2018/08/17');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('DB87', 95142101615, '2017/07/14', '2018/05/07');
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('YS88', 70650784376, '2017/03/21', null);
insert into sprzedawcy (id_dane_osobowe, pesel, data_zatrudnienia, data_zwolnienia) values ('AM89', 54538188084, '2017/01/30', '2018/04/30');

-- klienci
insert into klienci (id_dane_osobowe) values ('DP91');
insert into klienci (id_dane_osobowe) values ('KG92');
insert into klienci (id_dane_osobowe) values ('JG93');
insert into klienci (id_dane_osobowe) values ('HM94');
insert into klienci (id_dane_osobowe) values ('RM95');
insert into klienci (id_dane_osobowe) values ('BM96');
insert into klienci (id_dane_osobowe) values ('FG97');
insert into klienci (id_dane_osobowe) values ('TS98');
insert into klienci (id_dane_osobowe) values ('AC99');
insert into klienci (id_dane_osobowe) values ('KN100');
insert into klienci (id_dane_osobowe) values ('CV101');
insert into klienci (id_dane_osobowe) values ('LP102');
insert into klienci (id_dane_osobowe) values ('MS103');
insert into klienci (id_dane_osobowe) values ('FK104');
insert into klienci (id_dane_osobowe) values ('MS105');
insert into klienci (id_dane_osobowe) values ('IM106');
insert into klienci (id_dane_osobowe) values ('CB107');
insert into klienci (id_dane_osobowe) values ('TF108');
insert into klienci (id_dane_osobowe) values ('KW109');
insert into klienci (id_dane_osobowe) values ('AW110');
insert into klienci (id_dane_osobowe) values ('AM112');
insert into klienci (id_dane_osobowe) values ('CG113');
insert into klienci (id_dane_osobowe) values ('NY114');
insert into klienci (id_dane_osobowe) values ('BS115');
insert into klienci (id_dane_osobowe) values ('KL116');
insert into klienci (id_dane_osobowe) values ('DB117');
insert into klienci (id_dane_osobowe) values ('AB118');
insert into klienci (id_dane_osobowe) values ('AB119');
insert into klienci (id_dane_osobowe) values ('HH120');
insert into klienci (id_dane_osobowe) values ('KT121');
insert into klienci (id_dane_osobowe) values ('WD122');
insert into klienci (id_dane_osobowe) values ('BA123');
insert into klienci (id_dane_osobowe) values ('BS124');
insert into klienci (id_dane_osobowe) values ('SM125');
insert into klienci (id_dane_osobowe) values ('PC126');
insert into klienci (id_dane_osobowe) values ('JH127');
insert into klienci (id_dane_osobowe) values ('GK128');
insert into klienci (id_dane_osobowe) values ('BV129');
insert into klienci (id_dane_osobowe) values ('RT70');
insert into klienci (id_dane_osobowe) values ('BQ71');
insert into klienci (id_dane_osobowe) values ('MM72');
insert into klienci (id_dane_osobowe) values ('HE73');
insert into klienci (id_dane_osobowe) values ('NA74');
insert into klienci (id_dane_osobowe) values ('MD75');
insert into klienci (id_dane_osobowe) values ('EM76');
insert into klienci (id_dane_osobowe) values ('SL77');
insert into klienci (id_dane_osobowe) values ('EC78');
insert into klienci (id_dane_osobowe) values ('SB79');
insert into klienci (id_dane_osobowe) values ('RC80');
insert into klienci (id_dane_osobowe) values ('AL81');

-- gatunki
insert into gatunki (nazwa) values ('Drama');
insert into gatunki (nazwa) values ('Crime');
insert into gatunki (nazwa) values ('Comedy');
insert into gatunki (nazwa) values ('Romance');
insert into gatunki (nazwa) values ('Horror');
insert into gatunki (nazwa) values ('Thriller');
insert into gatunki (nazwa) values ('Musical');

-- rezyserzy 
insert into rezyserzy (imie, nazwisko) values ('Brit', 'Alvin');
insert into rezyserzy (imie, nazwisko) values ('Langsdon', 'MacKim');
insert into rezyserzy (imie, nazwisko) values ('Tedi', 'Aris');
insert into rezyserzy (imie, nazwisko) values ('Rivalee', 'Prier');
insert into rezyserzy (imie, nazwisko) values ('Errol', 'Coyte');

-- filmy
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'D70', 'Divorce - Italian Style (Divorzio all''italiana)', '2017/09/16', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'M76', 'Zeisters (Fat Guy Goes Nutzoid)', '2017/07/11', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'C72', 'The 39 Steps', '2018/09/05', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'H74', '22 Jump Street', '2017/07/02', 'cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'C72', 'Terminal Man, The', '2017/03/20', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'M76', 'The Little Kidnappers', '2017/08/18', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'D70', 'Born American', '2017/07/12', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'H74', 'Belarmino', '2017/11/19', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'C71', 'Stag', '2018/03/26', 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'H74', 'HazMat', '2018/04/25', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'D70', 'Pelle Svanslös i Amerikatt', '2018/05/04', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'C72', 'Blood Moon', '2017/06/18', 'eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'C71', 'Comrades: Almost a Love Story (Tian mi mi)', '2017/05/08', 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'C72', 'Comrades', '2018/08/02', 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'H74', 'Rushmore', '2018/01/17', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'C71', 'Wrong Arm of the Law, The', '2017/11/02', 'lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'C72', 'Lisa', '2017/12/08', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'H74', 'Turtles Can Fly (Lakposhtha hâm parvaz mikonand)', '2017/07/20', 'felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'H74', 'Unzipped', '2017/12/16', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'D70', 'Take, The', '2019/01/08', 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'T75', 'Perrier''s Bounty', '2018/11/28', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'T75', 'Secret, A (Un secret)', '2018/04/03', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('RP73REZ', 'H74', 'Bleach: Fade to Black (Bur&#299;chi Fade to Black Kimi no Na o Yobu)', '2018/01/21', 'blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('LM71REZ', 'H74', 'Hearts Divided', '2017/06/22', 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'C71', 'Laughing Woman, The (Frightened Woman, The) (Femina ridens)', '2018/02/25', 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'H74', 'Gauntlet, The', '2018/09/05', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'M76', 'Ungentlemanly Act, An', '2017/03/22', 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('BA70REZ', 'H74', 'Capricious Summer (Rozmarné léto)', '2017/12/11', 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('EC74REZ', 'M76', 'Alligator', '2017/03/17', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante');
insert into filmy (id_rezyser, id_gatunku, tytul, data_premiery, opis) values ('TA72REZ', 'R73', 'Little Witches', '2017/06/14', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');

-- seanse
insert into seanse (id_filmu, godzina_seansu) values ('ThC72EC74REZ72', '09:00');
insert into seanse (id_filmu, godzina_seansu) values ('22H74TA72REZ73', '11:00');
insert into seanse (id_filmu, godzina_seansu) values ('TeC72TA72REZ74', '13:00');
insert into seanse (id_filmu, godzina_seansu) values ('ThM76BA70REZ75', '15:00');
insert into seanse (id_filmu, godzina_seansu) values ('BoD70BA70REZ76', '17:00');
insert into seanse (id_filmu, godzina_seansu) values ('BeH74RP73REZ77', '19:00');
insert into seanse (id_filmu, godzina_seansu) values ('StC71LM71REZ78', '21:00');

-- miejsca
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('a', '17');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('b', '17');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('c', '17');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('d', '17');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('e', '17');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '01');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '02');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '03');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '04');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '05');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '06');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '07');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '08');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '09');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '10');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '11');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '12');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '13');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '14');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '15');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '16');
insert into miejsca (rzad_litera, fotel_cyfra) values ('f', '17');

-- bilety 
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0776', 'MD75113KL', 'CC8484SP', 'BoD70BA70REZ7613117', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e13150', null, 'AL8181SP', 'StC71LM71REZ7813321', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f13167', null, 'MM7272SP', 'TeC72TA72REZ7412913', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e15152', null, 'AM8989SP', 'StC71LM71REZ7813321', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d06126', null, 'EC7878SP', 'StC71LM71REZ7813321', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c09112', 'SM125133KL', 'YS8888SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d11131', 'DB117125KL', 'GB8282SP', '22H74TA72REZ7312811', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d02122', null, 'MM7272SP', 'BoD70BA70REZ7613117', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a1483', null, 'MD7575SP', 'StC71LM71REZ7813321', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f08162', null, 'EM7676SP', 'ThM76BA70REZ7513015', 'emeryt 8zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0776', 'HE73111KL', 'EM7676SP', 'ThC72EC74REZ7212709', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e16153', null, 'MW8585SP', 'TeC72TA72REZ7412913', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b0591', null, 'RC8080SP', '22H74TA72REZ7312811', 'ulgowy 12zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d08128', null, 'RC8080SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d12132', 'GK128136KL', 'GB8282SP', '22H74TA72REZ7312811', 'ulgowy 12zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b0591', 'AB118126KL', 'FA8686SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d12132', null, 'MM7272SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a1685', null, 'SB7979SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c16119', null, 'MD7575SP', 'BoD70BA70REZ7613117', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a1281', null, 'MM7272SP', 'StC71LM71REZ7813321', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0170', null, 'DB8787SP', '22H74TA72REZ7312811', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0574', 'CG113121KL', 'RC8080SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0675', 'PC126134KL', 'BQ7171SP', 'ThM76BA70REZ7513015', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b16102', 'KN10079KL', 'RC8080SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f07161', null, 'MW8585SP', 'TeC72TA72REZ7412913', 'ulgowy 12zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e14151', null, 'RT7070SP', 'BeH74RP73REZ7713219', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f17171', null, 'AM8989SP', 'BoD70BA70REZ7613117', 'emeryt 8zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b0692', null, 'PR8383SP', 'BeH74RP73REZ7713219', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c06109', null, 'HE7373SP', 'TeC72TA72REZ7412913', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f11165', 'AC9978KL', 'AM8989SP', '22H74TA72REZ7312811', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b17103', 'FK10483KL', 'PR8383SP', 'BoD70BA70REZ7613117', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c04107', null, 'PR8383SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f13167', null, 'RC8080SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('b0894', null, 'BQ7171SP', '22H74TA72REZ7312811', 'ulgowy 12zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0877', null, 'SB7979SP', 'BeH74RP73REZ7713219', 'ulgowy 12zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c05108', null, 'MW8585SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e16153', null, 'GB8282SP', 'TeC72TA72REZ7412913', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f05159', null, 'EM7676SP', 'BoD70BA70REZ7613117', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a1180', 'NY114122KL', 'PR8383SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f10164', null, 'SL7777SP', '22H74TA72REZ7312811', 'normalny 18zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('c03106', null, 'YS8888SP', 'BoD70BA70REZ7613117', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f08162', null, 'AL8181SP', 'StC71LM71REZ7813321', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f12166', null, 'YS8888SP', 'BoD70BA70REZ7613117', 'dziecko 4zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('d12132', 'AC9978KL', 'EM7676SP', 'StC71LM71REZ7813321', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f07161', 'RT70108KL', 'MD7575SP', 'TeC72TA72REZ7412913', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f05159', 'BV129137KL', 'EM7676SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e04141', null, 'DB8787SP', 'ThC72EC74REZ7212709', 'emeryt 8zl');
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('f10164', 'MM72110KL', 'AL8181SP', 'BeH74RP73REZ7713219', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('e17154', null, 'RC8080SP', 'TeC72TA72REZ7412913', null);
insert into bilety (id_miejsca, id_klient, id_sprzedawca, id_seansu, rodzaj_biletu) values ('a0271', null, 'EM7676SP', 'ThC72EC74REZ7212709', null);